name = "F#"
grammar = "fsharp"
path_suffixes = ["fs", "fsi", "fsx"]
line_comments = ["//"]
block_comment = ["(*", "*)"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "[|", end = "|]", close = true, newline = true },
    { start = "[<", end = ">]", close = true, newline = false },
]
word_characters = ["_", "'"]
tab_size = 4
